services:
  frontend:
    build:
      context: ./Frontend/portfolio-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend/portfolio-frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true